#!/bin/bash

# ==============================================================================
# Script Name : setup_dotnet_solution.sh
# Description : Automates the setup of a .NET Web Application solution with an
#               associated Class Library. Creates the solution layout, configures
#               project references, manages .gitignore, and optionally installs
#               client-side assets via LibMan.
# ==============================================================================

MyAppName="MyDemoApp"
WebAppName="DemoWebApp"
DemoClassLibName="DemoClassLib"

# Check if the target directory already exists
if [ -d "$MyAppName" ]; then
    echo "The directory '$MyAppName' already exists."

    read -t 5 -p "Do you want to remove it and continue? (Y/N) [Default: n]: " answer
    answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')
    if [ "$answer" == "y" ]; then
        echo "Removing existing directory..."
        rm -rf "$MyAppName"
    else
        echo "Operation cancelled."
        exit 1
    fi
fi

# Create solution layout
mkdir "$MyAppName" && cd "$MyAppName" || exit 1
dotnet new sln

# Create projects
dotnet new webapp --auth Individual -o "$WebAppName"
dotnet new classlib -o "$DemoClassLibName"

# Configure solution and project references
dotnet sln add "$WebAppName/$WebAppName.csproj"
dotnet sln add "$DemoClassLibName/$DemoClassLibName.csproj"
dotnet add "$WebAppName/$WebAppName.csproj" reference "$DemoClassLibName/$DemoClassLibName.csproj"

# Configure source control exclusions
dotnet new gitignore
# Exclude client libraries from source control to prevent repo bloat; these assets are automatically restorable via LibMan.
echo "**/wwwroot/lib/" >> .gitignore

echo "Update NuGet packages for all projects"
dotnet package update --project "$WebAppName"
dotnet package update --project "$DemoClassLibName"

echo ""
# Optional client-side asset setup via LibMan
read -t 5 -p "Would you like to automatically load third-party libraries using Microsoft LibMan? (Y/N) [Default: y]: " answer
answer=$(echo "$answer" | tr '[:upper:]' '[:lower:]')

# Use 'y' as the default if $answer is empty or 'y'
if [ -z "$answer" ] || [ "$answer" == "y" ]; then
    # Install the Microsoft LibraryManager (LibMan) global CLI tool.
    dotnet tool install --global Microsoft.Web.LibraryManager.Cli

    # Add the LibMan MSBuild integration package to the web application project file
    dotnet add package Microsoft.Web.LibraryManager.Build --project "$WebAppName"

    echo "Clearing default template client libraries..."
    rm -rf "$WebAppName/wwwroot/lib"

    # Navigate into the Web App directory to run LibMan commands
    cd "$WebAppName" || exit 1

    echo "Initializing LibMan..."
    libman init --default-provider cdnjs

    libman install bootstrap@5.3.8 --provider cdnjs --destination wwwroot/lib/bootstrap/dist
    libman install jquery@3.7.1 --provider cdnjs --destination wwwroot/lib/jquery/dist
    libman install jquery-validate@1.22.1 --provider cdnjs --destination wwwroot/lib/jquery-validation/dist
    libman install jquery-validation-unobtrusive@4.0.0 --provider cdnjs --destination wwwroot/lib/jquery-validation-unobtrusive/dist

    cd ..
else
    echo ""
    echo "----> Skipping LibMan configuration."
    echo "----> Using library files generated by 'dotnet new webapp' command at: $WebAppName/wwwroot/lib"
fi

# Build and execute the web application
dotnet run --project "$WebAppName" --launch-profile https
