# Example taken from https://github.com/khezen/compose-postgres
# https://hub.docker.com/_/postgres
# https://hub.docker.com/r/dpage/pgadmin4/

version: '3.7'

services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    hostname: pgSql1
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-userPwd1}
      PGDATA: /data/postgres
    volumes:
       - pgTestData:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - pgTestNetwork
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-adminPwd1}  # TODO: change this to a secure password
    volumes:
       - pgTestAdminData:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - pgTestNetwork
    restart: unless-stopped

networks:
  pgTestNetwork:
    driver: bridge

volumes:
    pgTestData:
    pgTestAdminData:
