# --- TO EXECUTE THIS FILE ---
# 1- Use the following command to create and start containers:
#    docker-compose up
#    (use the "-d" argument to run in "detached" mode).
# 2- To stop and remove containers, networks, images, and volumes:
#    docker-compose down
#    (use the "-v" argument to remove "volumes" created by docker-compose up).
# 3- Browse to: http://localhost:8080/ and select Create - Server in PgAdmin, Host name "${DB_HOST_NAME}" or 
#    browse to: http://localhost:8081/ and connect to system 'PostgreSQL' with "${DB_ROOT_USER}" user ID.

# https://docs.docker.com/compose/reference/
# https://docs.docker.com/compose/overview/

# https://www.postgresql.org/
# https://hub.docker.com/_/postgres
# https://hub.docker.com/r/dpage/pgadmin4/
# https://hub.docker.com/_/adminer/

services:
  postgresdb:
    container_name: postgres_container1
    image: postgres:latest
    hostname: "${DB_HOST_NAME}"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_ROOT_USER}"
      POSTGRES_PASSWORD: "${DB_ROOT_PW}"
      PGDATA: /var/lib/postgresql/data
    volumes:
       - dbfiles:/var/lib/postgresql/data
    ports:
      - "${DB_SRV_PORT}:5432"
    networks:
      - docknet
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container1
    hostname: pgadmin_host1
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}  # TODO: change this to a secure password
      # Configure authentication for SERVER mode or DESKTOP mode
      #PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgAdminFiles:/var/lib/pgadmin
    ports:
      - ${WEB_UI_1_PORT}:80
    networks:
      - docknet
    restart: always

  adminer:
    image: adminer:latest
    container_name: adminer_container1
    hostname: adminer1
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: "${DB_HOST_NAME}"
      ADMINER_DESIGN: mvt
    ports:
      - ${WEB_UI_2_PORT}:8080
    networks:
      - docknet

networks:
  docknet:
    driver: bridge

volumes:
    dbfiles:
    pgAdminFiles:
