# --- TO EXECUTE THIS FILE ---
# 1- Use the following command to create and start containers:
#    docker compose up
#    (use the "-d" argument to run in "detached" mode).
# 2- To stop and remove containers, networks, images, and volumes:
#    docker compose down
#    (use the "-v" argument to remove "volumes" created by docker compose up).
# 3- Browse to http://localhost:8080/ or http://localhost:8081/ and connect with either "root" or "${DB_USER}" user IDs.

# https://docs.docker.com/compose/reference/
# https://docs.docker.com/compose/overview/

# https://www.mysql.com/
# https://hub.docker.com/_/mysql
# https://hub.docker.com/r/phpmyadmin/phpmyadmin/
# https://hub.docker.com/_/adminer/

name: mysql
# https://docs.docker.com/compose/compose-file/

services:
  mysqldb:
    image: mysql:latest
    container_name: mysql_container1
    hostname: "${DB_HOST_NAME}"
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${USER_SECRET_KEY:?error}" # Get this password from an environment variable
      MYSQL_ROOT_PASSWORD: "${ADMIN_SECRET_KEY:?error}" # Get this password from an environment variable
    ports:
      # <Port Exposed> : <MySQL Port running inside the container>
      - ${DB_SRV_PORT}:3306
    volumes:
      - database_files:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p${ADMIN_SECRET_KEY} || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpMyAdmin_container1
    hostname: myAdmin1
    restart: always
    environment:
      PMA_HOST: mysqldb
      PMA_ARBITRARY: 1
    ports:
      - ${WEB_UI_1_PORT}:80
    depends_on:
      mysqldb:
        condition: service_healthy
  adminer:
    image: adminer:latest
    container_name: adminer_container1
    hostname: adminer1
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: "${DB_HOST_NAME}"
      ADMINER_DESIGN: mvt
      ADMINER_PLUGINS: dump-json dump-xml
    ports:
      - ${WEB_UI_2_PORT}:8080
    depends_on:
      mysqldb:
        condition: service_healthy
# Names our volume
volumes:
  database_files:
