# --- TO EXECUTE THIS FILE ---
# 1- To create and start containers use the following command:
#    docker-compose up
#    (you can use the "-d" argument to run in "detached" mode).
# 2- To stop and remove containers, networks, images, and volumes:
#    docker-compose down
#    (you can use the "-v" argument to remove "volumes" created by docker-compose up).
# 3- Browse to http://localhost:8080/ or http://localhost:8081/ and connect with either 'root' or 'testUser' user IDs.

# https://docs.docker.com/compose/reference/
# https://docs.docker.com/compose/overview/

# https://mariadb.com/
# https://hub.docker.com/_/mariadb
# https://hub.docker.com/r/phpmyadmin/phpmyadmin/
# https://hub.docker.com/_/adminer/
version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container1
    command: --default-authentication-plugin=mariadb_native_password
    hostname: mariadbsrv
    restart: always
    environment:
      MARIADB_DATABASE: MyTestDB
      MARIADB_USER: testUser
      MARIADB_PASSWORD: userPwd1
      MARIADB_ROOT_PASSWORD: rootPwd1 # TODO: change this to a secure password
    ports:
      # <Port Exposed> : <MariaDB Port running inside the container>
      - 3306:3306
    volumes:
      - myTestData:/var/lib/mysql
    networks:
      - docknet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myAdmin_container1
    hostname: myAdmin1
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    networks:
      - docknet
  adminer:
    image: adminer:latest
    container_name: adminer_container1
    hostname: adminer1
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: mvt
    ports:
      - 8081:8080
    networks:
      - docknet
# Names our volume
volumes:
  myTestData:

networks:
  docknet:
    driver: bridge
