# --- TO EXECUTE THIS FILE ---
# 1- Use the following command to create and start containers:
#    docker-compose up
#    (use the "-d" argument to run in "detached" mode).
# 2- To stop and remove containers, networks, images, and volumes:
#    docker-compose down
#    (use the "-v" argument to remove "volumes" created by docker-compose up).
# 3- Browse to http://localhost:8080/ or http://localhost:8081/ and connect with either 'root' or '${DB_USER}' user IDs.

# https://docs.docker.com/compose/reference/
# https://docs.docker.com/compose/overview/

# https://mariadb.com/
# https://hub.docker.com/_/mariadb
# https://hub.docker.com/r/phpmyadmin/phpmyadmin/
# https://hub.docker.com/_/adminer/

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container1
    command: --default-authentication-plugin=mariadb_native_password
    hostname: mariadbsrv
    restart: always
    environment:
      MARIADB_DATABASE: "${DB_NAME}"
      MARIADB_USER: "${DB_USER}"
      MARIADB_PASSWORD: "${DB_USER_PW}"
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PW}" # TODO: change this to a secure password
    ports:
      # <Port Exposed> : <MariaDB Port running inside the container>
      - ${DB_SRV_PORT}:3306
    volumes:
      - dbfiles:/var/lib/mysql
    networks:
      - docknet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myAdmin_container1
    hostname: myAdmin1
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_ARBITRARY: 1
    ports:
      - ${WEB_UI_1_PORT}:80
    networks:
      - docknet
  adminer:
    image: adminer:latest
    container_name: adminer_container1
    hostname: adminer1
    restart: always
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_SERVER: mariadb
      ADMINER_DESIGN: mvt
    ports:
      - ${WEB_UI_2_PORT}:8080
    networks:
      - docknet
# Names our volume
volumes:
  dbfiles:

networks:
  docknet:
    driver: bridge
